language: cpp
script:
  - git submodule update --init --recursive
  - export CXX="clang++ -isystem /usr/include/x86_64-linux-gnu/c++/4.8/ -isystem /usr/include/x86_64-linux-gnu"
  - export NINJA="./bin/ninja/ninja"
  - cd bin/ninja && ./bootstrap.py && ./configure.py && cd -
  - $NINJA
  - ./build/meka
compiler:
  - clang
before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo add-apt-repository -y "deb http://llvm.org/apt/saucy/ llvm-toolchain-saucy main"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get -qq install aptitude; sudo aptitude -yq2 update
  - sudo aptitude -yq2 full-upgrade -t trusty python
  - sudo aptitude -yq2 install -t trusty
      g++
      clang-3.4
      libboost1.54-all-dev
      cmake
      ninja-build
      libgl1-mesa-dev libegl1-mesa-dev libglu1-mesa-dev
